name: .NET Framework

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: windows-2019

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
      
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1.1

    - uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        # Look to see if there is a cache hit for the corresponding requirements file
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget

    - name: Restore Packages
      run: nuget restore MediaControl.sln

    - name: Build solution
      run: msbuild MediaControl.sln -t:rebuild -property:Configuration=Release

    - name: Publish
      uses: actions/upload-artifact@master
      with:
        name: mb_MediaControl
        path: |
          ${{ github.workspace }}/bin/Release/mb_MediaControl.dll
          ${{ github.workspace }}/bin/Release/Gma.System.MouseKeyHook.dll
